# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Spark Sampler CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Run Compile & Test
      run: sbt compile test
      env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Packaging
      run: sbt package
      env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
    - name: Sampler jar Assembly
      run: sbt assembly
      env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    #- name: Publish to github package
    #  run: sbt publish
    #  env:
    #      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
