# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Spark Sampler CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Run Compile
      run: sbt compile
      env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
  # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
  #  - name: Upload dependency graph
  #    uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
    - name: Packaging
      run: sbt package
      env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
    - name: Sampler jar Assembly
      run: sbt assembly
      env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    - name: Publish to github package
      run: sbt publish
      env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
